- name: Build Angular App
  hosts: buildserver
  gather_facts: no
  become: yes
  vars:
    version: "{{ version | default('v1.0.0') }}"
    project_dir: "{{ project_dir | default('/tmp/angular-app') }}"
    artifact_dir: /tmp/angular-artifacts

  tasks:

    - name: Ensure Angular CLI is installed
      shell: npm list -g @angular/cli || npm install -g @angular/cli

    - name: Install project dependencies
      shell: npm install
      args:
        chdir: "{{ project_dir }}"

    - name: Build Angular app (with verbose)
      shell: ./node_modules/.bin/ng build --configuration production --verbose
      args:
        chdir: "{{ project_dir }}"
      register: build_output
      ignore_errors: yes

    - name: Fail if Angular build really failed
      fail:
        msg: "Angular build failed:\n{{ build_output.stderr }}"
      when: build_output.rc != 0

    - name: Create tar.gz artifact
      shell: |
        mkdir -p {{ artifact_dir }}
        tar -czvf {{ artifact_dir }}/angular-devops-{{ version }}.tar.gz -C {{ project_dir }}/dist .
      register: tar_output
