- name: Build Angular App
  hosts: buildserver
  gather_facts: no
  become: yes
  vars:
    version: "{{ version | default('v1.0.0') }}"
    project_dir: "{{ project_dir | default('/tmp/angular-app') }}"
    artifact_dir: /tmp/angular-artifacts

  tasks:

    - name: Ensure jq is installed (optional)
      package:
        name: jq
        state: present

    - name: Remove "target" from tsconfig.json using regex (fallback for jq)
      replace:
        path: "{{ project_dir }}/tsconfig.json"
        regexp: '\s*"target"\s*:\s*"[^"]*",?\n?'
        replace: ''

    - name: Ensure .browserslistrc exists with modern config (no ES5 targets)
      copy:
        dest: "{{ project_dir }}/.browserslistrc"
        content: |
          last 2 Chrome versions
          last 2 Firefox versions
          last 2 Edge versions
          last 2 Safari versions
          > 1%
          not dead
          not op_mini all
          not kaios 2.5
        force: yes

    - name: Ensure Angular CLI is installed globally
      shell: npm list -g @angular/cli || npm install -g @angular/cli

    - name: Install project dependencies
      shell: npm install
      args:
        chdir: "{{ project_dir }}"

    - name: Build Angular app (with verbose output)
      shell: ./node_modules/.bin/ng build --configuration production --verbose
      args:
        chdir: "{{ project_dir }}"
      register: build_output
      ignore_errors: true

    - name: Fail if Angular build failed
      fail:
        msg: "Angular build failed:\n{{ build_output.stderr }}"
      when: build_output.rc != 0

    - name: Create tar.gz artifact from dist folder
      shell: |
        mkdir -p {{ artifact_dir }}
        tar -czvf {{ artifact_dir }}/angular-devops-{{ version }}.tar.gz -C {{ project_dir }}/dist .
      register: tar_output
