---
- name: Deploy Angular App to Apache Server
  hosts: webservers
  become: true
  vars:
    version: "{{ version | default('v1.0.0') }}"
    artifact_name: "angular-devops-{{ version }}.tar.gz"
    artifact_path: "/tmp/{{ artifact_name }}"
    deploy_dir: "/var/www/html/angular-app"

  roles:
    - apache
    - angular
