---
- name: Deploy Angular App to Apache Server
  hosts: webservers
  become: true
  vars:
    version: "{{ version | default('v1.0.0') }}"
    artifact_name: "angular-devops-{{ version }}.tar.gz"
    workspace: "{{ workspace | default('/var/lib/jenkins/workspace') }}"
    artifact_src: "{{ workspace }}/{{ artifact_name }}"
    artifact_dest: "/tmp/{{ artifact_name }}"
    deploy_dir: "/var/www/html/angular-app"

  tasks:
    - name: Check artifact exists locally on Jenkins
      ansible.builtin.stat:
        path: "{{ artifact_src }}"
      register: artifact_check
      delegate_to: localhost
      become: false
      failed_when: not artifact_check.stat.exists

    - name: Install Apache
      package:
        name: apache2
        state: present

    - name: Ensure deploy directory exists
      file:
        path: "{{ deploy_dir }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Copy artifact to deploy server
      copy:
        src: "{{ artifact_src }}"
        dest: "{{ artifact_dest }}"

    - name: Extract Angular artifact
      unarchive:
        src: "{{ artifact_dest }}"
        dest: "{{ deploy_dir }}"
        remote_src: yes
        owner: www-data
        group: www-data

    - name: Restart Apache service
      service:
        name: apache2
        state: restarted
        enabled: yes
