---
- name: Deploy Angular App to Apache Server
  hosts: webservers
  become: true
  vars:
    version: "{{ version | default('v1.0.0') }}"
    artifact_name: "angular-devops-{{ version }}.tar.gz"
    artifact_src: "/var/lib/jenkins/ansible/artifacts/{{ artifact_name }}"
    artifact_dest: "/tmp/{{ artifact_name }}"
    deploy_dir: "/var/www/html/angular-app"

  tasks:
    - name: Check artifact exists locally on Jenkins
      local_action:
        module: command
        args:
          cmd: ls -l "{{ artifact_src }}"
      become: false

    - name: Install Apache
      package:
        name: apache2
        state: present

    - name: Ensure deploy directory exists
      file:
        path: "{{ deploy_dir }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Copy artifact to deploy server
      copy:
        src: "{{ artifact_src }}"
        dest: "{{ artifact_dest }}"

    - name: Extract Angular artifact
      unarchive:
        src: "{{ artifact_dest }}"
        dest: "{{ deploy_dir }}"
        remote_src: yes
        owner: www-data
        group: www-data

    - name: Restart Apache service
      service:
        name: apache2
        state: restarted
        enabled: yes
