---
- name: Run Angular Tests
  hosts: buildserver
  become: yes
  gather_facts: no

  vars:
    project_dir: "{{ project_dir | default('/tmp/angular-app') }}"

  tasks:
    - name: Ensure required tools are present
      package:
        name:
          - wget
          - gnupg
          - ca-certificates
        state: present

    - name: Install project dependencies (with peer dep workaround)
      shell: npm install --legacy-peer-deps
      args:
        chdir: "{{ project_dir }}"

    - name: Run Angular unit tests with Jest
      shell: npm test
      args:
        chdir: "{{ project_dir }}"
