---
- name: Run Angular Tests
  hosts: buildserver
  become: yes
  gather_facts: yes

  vars:
    project_dir: /home/ubuntu/angular-app  # ✅ Update this path accordingly

  tasks:
    - name: Ensure dependencies are installed
      shell: npm install
      args:
        chdir: "{{ project_dir }}"

    - name: Run Angular unit tests (headless)
      shell: npm test --watch=false
      args:
        chdir: "{{ project_dir }}"
...
