---
- name: Run Angular Tests
  hosts: buildserver
  become: yes
  gather_facts: no

  vars:
    project_dir: "{{ project_dir | default('/tmp/angular-app') }}"

  tasks:
    - name: Ensure required tools are present
      package:
        name:
          - wget
          - gnupg
          - ca-certificates
        state: present

    - name: Add Google Chrome signing key
      apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub
        state: present

    - name: Add Google Chrome APT repository
      apt_repository:
        repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
        state: present
        filename: google-chrome

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Google Chrome stable
      apt:
        name: google-chrome-stable
        state: present

    - name: Install project dependencies
      shell: npm install
      args:
        chdir: "{{ project_dir }}"

    - name: Run Angular unit tests (headless)
      shell: npm test --watch=false
      args:
        chdir: "{{ project_dir }}"
