---
- name: Run Angular Tests
  hosts: buildserver
  become: yes
  gather_facts: no

  vars:
    project_dir: "{{ project_dir | default('/tmp/angular-app') }}"  # Now it's dynamic and works with Jenkins

  tasks:
    - name: Ensure dependencies are installed
      shell: npm install
      args:
        chdir: "{{ project_dir }}"

    - name: Run Angular unit tests (headless)
      shell: npm test --watch=false --browsers=ChromeHeadless
      args:
        chdir: "{{ project_dir }}"
...
