---
- name: Install Apache
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Start and enable Apache
  service:
    name: apache2
    state: started
    enabled: true

- name: Set Apache docroot to symlink
  lineinfile:
    path: /etc/apache2/sites-available/000-default.conf
    regexp: '^DocumentRoot'
    line: 'DocumentRoot /var/www/html/current'

- name: Reload Apache
  service:
    name: apache2
    state: reloaded
...
